### ISSUE TITLE
Cannot download flash files from /f/ with lurk mode

### ISSUE THREAD

**Issue by wewman** [wewman/4bash#3]
Directories are created, .json and .files are downloaded, but the files itself are not.

I will take a look into it soon, but if you wish, go ahead.

**Comment by 813gan** [comment]
"Normal" mode dont work too. On /f/ link to file is build of "filename", not "tim".
Additionally filename from api is not url encoded and if these filenames can contain non-ASCII characters or newline we cant use sed.
Update: filenames may contain Unicode emojis like ♂. I have unfinished url-encoder in Python https://gist.github.com/813gan/ded20a7cd45cb53dafcde1d0863132cc ,  at the moment it can take text as argument and return percent-encoded string.

**Comment by 813gan** [comment]
We dont need Python, jq is able to URL-encode string.
`echo '"test test"' | jq '@uri'`

**Comment by wewman** [comment]
I might have some time this week to do some stuff for this.

**Comment by 813gan** [comment]
Fixed in #5  ;)

**Comment by 813gan** [comment]
But to be honest 'lurk mode' is useless on /f/. Comments and titles are nearly random there.
